name: Docker

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/docker.yml
      - Dockerfile
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1
        with:
          ref: ${{ github.ref }}
          check-name: Build
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
